export const JOIN_REQUEST = 'JOIN_REQUEST';
export const JOIN_SUCCESS = 'JOIN_SUCCESS';
export const JOIN_FAILURE = 'JOIN_FAILURE';

export const LOG_IN_REQUEST = 'LOG_IN_REQUEST';
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE';

export const LOG_OUT_REQUEST = 'LOG_OUT_REQUEST';
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';
export const LOG_OUT_FAILURE = 'LOG_OUT_FAILURE';

export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_FAILURE = 'LOAD_USER_FAILURE';

export const PLAY_TRACK = 'PLAY_TRACK';
export const PAUSE_TRACK = 'PAUSE_TRACK';
export const SET_TRACK_PLAYTIME = 'SET_TRACK_PLAYTIME';

export const WATCH_TRACK_PLAYING = 'WATCH_TRACK_PLAYING';
export const PLAY_NEXT_TRACK = 'PLAY_NEXT_TRACK';
export const PLAY_PREV_TRACK = 'PLAY_PREV_TRACK';
export const ADD_TO_UPNEXT = 'ADD_TO_UPNEXT';
export const ADD_TO_UPNEXT_AND_PLAY = 'ADD_TO_UPNEXT_AND_PLAY';
export const DELETE_TRACK_FROM_UPNEXT = 'DELETE_TRACK_FROM_UPNEXT';